// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package query

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryNotification struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryNotification) Reset()         { *m = QueryNotification{} }
func (m *QueryNotification) String() string { return proto.CompactTextString(m) }
func (*QueryNotification) ProtoMessage()    {}
func (*QueryNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *QueryNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryNotification.Unmarshal(m, b)
}
func (m *QueryNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryNotification.Marshal(b, m, deterministic)
}
func (m *QueryNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNotification.Merge(m, src)
}
func (m *QueryNotification) XXX_Size() int {
	return xxx_messageInfo_QueryNotification.Size(m)
}
func (m *QueryNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNotification.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNotification proto.InternalMessageInfo

func (m *QueryNotification) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type QueryNotificationResponse struct {
	Status               uint32   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryNotificationResponse) Reset()         { *m = QueryNotificationResponse{} }
func (m *QueryNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNotificationResponse) ProtoMessage()    {}
func (*QueryNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *QueryNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryNotificationResponse.Unmarshal(m, b)
}
func (m *QueryNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryNotificationResponse.Marshal(b, m, deterministic)
}
func (m *QueryNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNotificationResponse.Merge(m, src)
}
func (m *QueryNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_QueryNotificationResponse.Size(m)
}
func (m *QueryNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNotificationResponse proto.InternalMessageInfo

func (m *QueryNotificationResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryNotification)(nil), "QueryNotification")
	proto.RegisterType((*QueryNotificationResponse)(nil), "QueryNotificationResponse")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2c, 0x4d, 0x2d,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x20,
	0x0a, 0x94, 0x9c, 0xb9, 0x04, 0x03, 0x41, 0xea, 0xfd, 0xf2, 0x4b, 0x32, 0xd3, 0x32, 0x93, 0x13,
	0x4b, 0x32, 0xf3, 0xf3, 0x84, 0xf4, 0xb8, 0x58, 0x42, 0x32, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18,
	0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0x86, 0xe8, 0xc1, 0x0c, 0xd1, 0x0b, 0x81, 0x19, 0x12, 0x04,
	0x56, 0xa7, 0x64, 0xcc, 0x25, 0x89, 0x61, 0x48, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa,
	0x90, 0x18, 0x17, 0x5b, 0x70, 0x49, 0x62, 0x49, 0x69, 0x31, 0xd8, 0x38, 0xde, 0x20, 0x28, 0xcf,
	0xc8, 0x89, 0x8b, 0x15, 0xac, 0x49, 0xc8, 0x92, 0x8b, 0xd5, 0x31, 0x27, 0xb5, 0xa8, 0x44, 0x48,
	0x48, 0x0f, 0xc3, 0x14, 0x29, 0x29, 0x3d, 0x9c, 0x26, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x9d, 0x64,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x3a, 0xdc, 0x63, 0xf4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Alert(ctx context.Context, in *QueryNotification, opts ...grpc.CallOption) (*QueryNotificationResponse, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Alert(ctx context.Context, in *QueryNotification, opts ...grpc.CallOption) (*QueryNotificationResponse, error) {
	out := new(QueryNotificationResponse)
	err := c.cc.Invoke(ctx, "/Query/Alert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Alert(context.Context, *QueryNotification) (*QueryNotificationResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Alert(ctx context.Context, req *QueryNotification) (*QueryNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alert not implemented")
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Alert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Alert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Query/Alert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Alert(ctx, req.(*QueryNotification))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alert",
			Handler:    _Query_Alert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query.proto",
}
