// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package contradb

var TableNames = struct {
	Config      string
	Lease       string
	Log         string
	Reservation string
	Rule        string
}{
	Config:      "config",
	Lease:       "lease",
	Log:         "log",
	Reservation: "reservation",
	Rule:        "rule",
}
