// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package contradb

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testConfigs(t *testing.T) {
	t.Parallel()

	query := Configs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testConfigsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testConfigsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Configs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testConfigsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ConfigSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testConfigsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ConfigExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Config exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ConfigExists to return true, but got false.")
	}
}

func testConfigsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	configFound, err := FindConfig(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if configFound == nil {
		t.Error("want a record, got nil")
	}
}

func testConfigsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Configs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testConfigsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Configs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testConfigsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	configOne := &Config{}
	configTwo := &Config{}
	if err = randomize.Struct(seed, configOne, configDBTypes, false, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}
	if err = randomize.Struct(seed, configTwo, configDBTypes, false, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = configOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = configTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Configs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testConfigsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	configOne := &Config{}
	configTwo := &Config{}
	if err = randomize.Struct(seed, configOne, configDBTypes, false, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}
	if err = randomize.Struct(seed, configTwo, configDBTypes, false, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = configOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = configTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func configBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func configAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Config) error {
	*o = Config{}
	return nil
}

func testConfigsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Config{}
	o := &Config{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, configDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Config object: %s", err)
	}

	AddConfigHook(boil.BeforeInsertHook, configBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	configBeforeInsertHooks = []ConfigHook{}

	AddConfigHook(boil.AfterInsertHook, configAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	configAfterInsertHooks = []ConfigHook{}

	AddConfigHook(boil.AfterSelectHook, configAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	configAfterSelectHooks = []ConfigHook{}

	AddConfigHook(boil.BeforeUpdateHook, configBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	configBeforeUpdateHooks = []ConfigHook{}

	AddConfigHook(boil.AfterUpdateHook, configAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	configAfterUpdateHooks = []ConfigHook{}

	AddConfigHook(boil.BeforeDeleteHook, configBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	configBeforeDeleteHooks = []ConfigHook{}

	AddConfigHook(boil.AfterDeleteHook, configAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	configAfterDeleteHooks = []ConfigHook{}

	AddConfigHook(boil.BeforeUpsertHook, configBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	configBeforeUpsertHooks = []ConfigHook{}

	AddConfigHook(boil.AfterUpsertHook, configAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	configAfterUpsertHooks = []ConfigHook{}
}

func testConfigsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testConfigsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(configColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testConfigsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testConfigsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ConfigSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testConfigsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Configs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	configDBTypes = map[string]string{`ID`: `integer`, `Sources`: `ARRAYtext`, `SearchDomains`: `ARRAYtext`, `DomainNeeded`: `boolean`, `SpoofedA`: `text`, `SpoofedAaaa`: `text`, `SpoofedCname`: `text`, `SpoofedDefault`: `text`}
	_             = bytes.MinRead
)

func testConfigsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(configPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(configAllColumns) == len(configPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, configDBTypes, true, configPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testConfigsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(configAllColumns) == len(configPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Config{}
	if err = randomize.Struct(seed, o, configDBTypes, true, configColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, configDBTypes, true, configPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(configAllColumns, configPrimaryKeyColumns) {
		fields = configAllColumns
	} else {
		fields = strmangle.SetComplement(
			configAllColumns,
			configPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ConfigSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testConfigsUpsert(t *testing.T) {
	t.Parallel()

	if len(configAllColumns) == len(configPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Config{}
	if err = randomize.Struct(seed, &o, configDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Config: %s", err)
	}

	count, err := Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, configDBTypes, false, configPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Config struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Config: %s", err)
	}

	count, err = Configs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
