// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package contradb

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testLeases(t *testing.T) {
	t.Parallel()

	query := Leases()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testLeasesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLeasesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Leases().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLeasesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LeaseSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLeasesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := LeaseExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Lease exists: %s", err)
	}
	if !e {
		t.Errorf("Expected LeaseExists to return true, but got false.")
	}
}

func testLeasesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	leaseFound, err := FindLease(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if leaseFound == nil {
		t.Error("want a record, got nil")
	}
}

func testLeasesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Leases().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testLeasesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Leases().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testLeasesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	leaseOne := &Lease{}
	leaseTwo := &Lease{}
	if err = randomize.Struct(seed, leaseOne, leaseDBTypes, false, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}
	if err = randomize.Struct(seed, leaseTwo, leaseDBTypes, false, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = leaseOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = leaseTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Leases().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testLeasesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	leaseOne := &Lease{}
	leaseTwo := &Lease{}
	if err = randomize.Struct(seed, leaseOne, leaseDBTypes, false, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}
	if err = randomize.Struct(seed, leaseTwo, leaseDBTypes, false, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = leaseOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = leaseTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func leaseBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func leaseAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Lease) error {
	*o = Lease{}
	return nil
}

func testLeasesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Lease{}
	o := &Lease{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, leaseDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Lease object: %s", err)
	}

	AddLeaseHook(boil.BeforeInsertHook, leaseBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	leaseBeforeInsertHooks = []LeaseHook{}

	AddLeaseHook(boil.AfterInsertHook, leaseAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	leaseAfterInsertHooks = []LeaseHook{}

	AddLeaseHook(boil.AfterSelectHook, leaseAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	leaseAfterSelectHooks = []LeaseHook{}

	AddLeaseHook(boil.BeforeUpdateHook, leaseBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	leaseBeforeUpdateHooks = []LeaseHook{}

	AddLeaseHook(boil.AfterUpdateHook, leaseAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	leaseAfterUpdateHooks = []LeaseHook{}

	AddLeaseHook(boil.BeforeDeleteHook, leaseBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	leaseBeforeDeleteHooks = []LeaseHook{}

	AddLeaseHook(boil.AfterDeleteHook, leaseAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	leaseAfterDeleteHooks = []LeaseHook{}

	AddLeaseHook(boil.BeforeUpsertHook, leaseBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	leaseBeforeUpsertHooks = []LeaseHook{}

	AddLeaseHook(boil.AfterUpsertHook, leaseAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	leaseAfterUpsertHooks = []LeaseHook{}
}

func testLeasesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLeasesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(leaseColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLeasesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLeasesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LeaseSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLeasesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Leases().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	leaseDBTypes = map[string]string{`ID`: `bigint`, `Time`: `timestamp without time zone`, `Source`: `text`, `Op`: `character`, `Mac`: `macaddr`, `IP`: `inet`, `Hostname`: `text`, `Vendor`: `text`}
	_            = bytes.MinRead
)

func testLeasesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(leasePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(leaseAllColumns) == len(leasePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, leaseDBTypes, true, leasePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testLeasesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(leaseAllColumns) == len(leasePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Lease{}
	if err = randomize.Struct(seed, o, leaseDBTypes, true, leaseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, leaseDBTypes, true, leasePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(leaseAllColumns, leasePrimaryKeyColumns) {
		fields = leaseAllColumns
	} else {
		fields = strmangle.SetComplement(
			leaseAllColumns,
			leasePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := LeaseSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testLeasesUpsert(t *testing.T) {
	t.Parallel()

	if len(leaseAllColumns) == len(leasePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Lease{}
	if err = randomize.Struct(seed, &o, leaseDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Lease: %s", err)
	}

	count, err := Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, leaseDBTypes, false, leasePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Lease struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Lease: %s", err)
	}

	count, err = Leases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
