// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package contradb

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Configs", testConfigsUpsert)

	t.Run("Leases", testLeasesUpsert)

	t.Run("Logs", testLogsUpsert)

	t.Run("Reservations", testReservationsUpsert)

	t.Run("Rules", testRulesUpsert)
}
