DROP TABLE IF EXISTS blacklist CASCADE;
DROP TABLE IF EXISTS config CASCADE;
DROP TABLE IF EXISTS lease CASCADE;
DROP TABLE IF EXISTS log CASCADE;
DROP TABLE IF EXISTS oui CASCADE;
DROP TABLE IF EXISTS reservation CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS whitelist CASCADE;
