package rulegen

// https://someonewhocares.org/hosts/hosts
var testSet1 = []string{
   "a.ads2.msads.net",
   "adnexus.net",
   "aidps.atdmt.com",
   "az361816.vo.msecnd.net",
   "az512334.vo.msecnd.net",
   "b.ads1.msn.com",
   "b.ads2.msads.net",
   "c.atdmt.com",
   "c.msn.com",
   "cdn.atdmt.com",
   "cds26.ams9.msecn.net",
   "db3aqu.atdmt.com",
   "ec.atdmt.com",
   "feedback.microsoft-hohm.com",
   "flex.msn.com",
   "g.msn.com",
   "h1.msn.com",
   "lb1.www.ms.akadns.net",
   "live.rads.msn.com",
   "m.adnxs.com",
   "msnbot-65-55-108-23.search.msn.com",
   "msntest.serving-sys.com",
   "preview.msn.com",
   "reports.wes.df.telemetry.microsoft.com", // <-
   "schemas.microsoft.akadns.net",
   "secure.flashtalking.com",
   "settings-win.data.microsoft.com",
   "sO.2mdn.net",
   "statsfe2.ws.microsoft.com",
   "telemetry.appex.bing.net",
   "v10.vortex-win.data.microsoft.com", // <-
   "vortex-win.data.microsoft.com",
   "wes.df.telemetry.microsoft.com",
}

var testSet1Res1 = []string{
   "a.ads2.msads.net",
   "adnexus.net",
   "aidps.atdmt.com",
   "az361816.vo.msecnd.net",
   "az512334.vo.msecnd.net",
   "b.ads1.msn.com",
   "b.ads2.msads.net",
   "c.atdmt.com",
   "c.msn.com",
   "cdn.atdmt.com",
   "cds26.ams9.msecn.net",
   "db3aqu.atdmt.com",
   "ec.atdmt.com",
   "feedback.microsoft-hohm.com",
   "flex.msn.com",
   "g.msn.com",
   "h1.msn.com",
   "lb1.www.ms.akadns.net",
   "live.rads.msn.com",
   "m.adnxs.com",
   "msnbot-65-55-108-23.search.msn.com",
   "msntest.serving-sys.com",
   "preview.msn.com",
   "schemas.microsoft.akadns.net",
   "secure.flashtalking.com",
   "settings-win.data.microsoft.com",
   "sO.2mdn.net",
   "statsfe2.ws.microsoft.com",
   "telemetry.appex.bing.net",
   "vortex-win.data.microsoft.com",
   "wes.df.telemetry.microsoft.com",
}

var testSet1Res2 = []string{
    "a.ads2.msads.net",
    "adnexus.net",
    "aidps.atdmt.com",
    "az361816.vo.msecnd.net",
    "az512334.vo.msecnd.net",
    "b.ads1.msn.com",
    "b.ads2.msads.net",
    "c.atdmt.com",
    "c.msn.com",
    "cdn.atdmt.com",
    "cds26.ams9.msecn.net",
    "db3aqu.atdmt.com",
    "ec.atdmt.com",
    "feedback.microsoft-hohm.com",
    "flex.msn.com",
    "g.msn.com",
    "h1.msn.com",
    "lb1.www.ms.akadns.net",
    "live.rads.msn.com",
    "m.adnxs.com",
    "msnbot-65-55-108-23.search.msn.com",
    "msntest.serving-sys.com",
    "preview.msn.com",
    "schemas.microsoft.akadns.net",
    "secure.flashtalking.com",
    "sO.2mdn.net",
    "telemetry.appex.bing.net",
    "microsoft.com",
}
