[psql]
  host    = "localhost"
  port    = 5432
  dbname  = "contradb"
  user    = "contradbmgr"
  pass    = "contradbmgr"
  schema  = "public"
  sslmode = "disable"

  blacklist = ["lease_details", "log_block_details", "log_details_recent", "oui"]
